### PR TITLE
implemented production FMOD banks, 3D footstep sounds

### PR DESCRIPTION
**Pull request by jackcaunter**
built audio banks to Assets\Game\Audio\ProductionAudioBanks_JackAndNik
added fmod event to NellController.cs
attached fmod listener component to main camera

### CODE REVIEW

**Review by bennieb1 — COMMENTED** [review]
can u resolve conflicts anything fmod related to master level just update from your version

**Comment by jackcaunter** [comment]
> can u resolve conflicts anything fmod related to master level just update from your version

i think it would be a better idea for you to resolve the merge conflicts because you're more familiar with the main repo. i don't know what's conflicting or what's important in the main dev branch

**Review by bennieb1 — COMMENTED** [review]
Github won't let me resolve the conflict but from what I can tell it's the fmod.log file and u will want your version so I assume If u update branch from developing you'll get a error click resolve then your branch name

**Comment by jackcaunter** [comment]
> Github won't let me resolve the conflict but from what I can tell it's the fmod.log file and u will want your version so I assume If u update branch from developing you'll get a error click resolve then your branch name

GitHubDesktop_FJhKzxHwo2
yeah, i think you have to review it before it can be merged. i don't have permission to merge into Developing because it's not my role

**Review by bennieb1 — APPROVED** [review]

**Pull request merged**
